### ISSUE TITLE
Calcul metrique date AttributeError: Can only use .dt accessor with datetimelike values

### ISSUE THREAD

**Issue by jaalmoes** [beng-git/DARC2022#6]
Bonjour,

J'essai de calculer le score mais je reçois une erreur de pandas dans le fichier dateUtil.py (que je n'ai pas modifié)

voici l'erruer :

`Traceback (most recent call last):
  File "/home/jaalmoes/inria/these_2022/apvp/challenge/source_file/main.py", line 15, in <module>
    util_val = u.main(anon_data, original_data, params, nb_original_lines)
  File "/home/jaalmoes/inria/these_2022/apvp/challenge/source_file/utility.py", line 10, in main
    dat_val = date(df_anon, df_original, nb_orig_lines)
  File "/home/jaalmoes/inria/these_2022/apvp/challenge/source_file/dateUtil.py", line 25, in main
    df_date_utility = pd.DataFrame({ 'DayOfTheWeek_orig': df_orig['DateTime'].dt.dayofweek, 'DayOfTheWeek_anon': df_anon['DateTime'].dt.dayofweek, 'Week_orig':df_orig['DateTime'].dt.isocalendar().week, 'Week_anon': df_anon['DateTime'].dt.isocalendar().week })
  File "/home/jaalmoes/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5583, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/jaalmoes/.local/lib/python3.10/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/jaalmoes/.local/lib/python3.10/site-packages/pandas/core/indexes/accessors.py", line 509, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values. Did you mean: 'at'`

et voici le code que j'ai utilisé : 
`import pandas as pd

from dateUtil import main as date

original_data = pd.read_csv('short.csv',sep='\t',header=None, names=['ID','DateTime','lon','lat'])
nb_original_lines = len(original_data)
anon_data = pd.read_csv('short.csv',sep='\t',header=None, names=['ID','DateTime','lat','lon'])
anon_data = anon_data.loc[anon_data.ID !='DEL ']
df_original_without_DEL = original_data.loc[anon_data.index]

print("LOADED")

util_val = date(anon_data, original_data, nb_original_lines)
print(util_val)`

Je dois surement faire quelque chose de mal car apparement les autres n'ont pas cette erreur.

**Comment by jaalmoes** [comment]
C'était bien de ma faute ! Désolé
